// Generated by Wrangler on Fri Jun 21 2024 12:24:47 GMT+0200 (Central European Summer Time)
// by running `wrangler types app/bindings.d.ts`

export {};
declare global {
	const DOCUMENTS: KVNamespace;
	const SESSION_SECRET: "";
	const SESSION_STORAGE: "";
	const GRAPH_JSON_API_KEY: "";
	const APIHERO_PROJECT_KEY: "";
}
